name: dufuna
description: Dufuna flutter app.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.3.1
  connectivity: ^3.0.3
  dartz: ^0.10.1
  dio: ^4.0.4
  firebase_app_check: ^0.1.1+13
  firebase_auth: ^4.2.5
  firebase_core: ^2.5.0
  firebase_storage: ^11.0.13
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.2.0
  flutter_form_builder: 7.0.0
  flutter_native_splash: ^2.2.19
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.4.0
  form_builder_validators: ^8.1.1
  get_it: ^7.2.0
  google_sign_in: ^6.0.2
  image_picker: ^0.8.4+8
  intl: null
  lottie: ^2.3.0
  mailer: ^6.0.0
  permission_handler_android: null
  phosphor_flutter: ^1.4.0
  provider: ^6.0.2
  supabase_flutter: ^1.6.2
  toast: ^0.2.9
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
  fonts:
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

lottie: ^1.1.0
