name: dufuna
description: Dufuna flutter app.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.2.1
  connectivity: ^3.0.3
  dartz: ^0.10.1
  dio: ^4.0.4
  firebase_core: ^2.5.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  image_picker: ^0.8.4+8
  intl: 
  phosphor_flutter: ^1.4.0
  provider: ^6.0.2
  google_sign_in: ^5.4.3
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.13
  flutter_form_builder: 7.0.0
  form_builder_validators: ^8.1.1
  toast: ^0.2.9


  permission_handler_android:



dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

lottie: ^1.1.0
